[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std=lib/forge-std/src/",
    "foundry-huff=lib/foundry-huff/src/",
    "@hack/=src/",
    "solmate/=lib/solmate/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink=lib/chainlink/contracts/src/v0.8/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
