[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# solc_version = '0.8.13'
# evm_version = 'Shanghai'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200 # Default amount
ffi = true
fuzz_runs = 1_000
remappings = [
    "forge-std=lib/forge-std/src/",
    "foundry-huff=lib/foundry-huff/src/",
    "@hack/=src/",
    "solmate/=lib/solmate/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink=lib/chainlink/contracts/src/v0.8/shared/",
  
]
fs_permissions = [
    { access = "read", path = "./test/erc721/wrapper.huff" }
]

[profile.default.fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
